name: Sql Server data lib

on:

  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'src/services/common/Codebreaker.Data.SqlServer/**'

  # Allow manually trigger 
  workflow_dispatch:    

jobs:
  build:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/createnuget-withbuildnumber.yml@main
    with:
      version-suffix: preview.1.
      version-number: ${{ github.run_number }}
      version-offset: 10
      solutionfile-path: src/Codebreaker.Backend.SqlServer.slnx
      projectfile-path: src/services/common/Codebreaker.Data.SqlServer/Codebreaker.Data.SqlServer.csproj
      dotnet-version: '9.0.x'
      artifact-name: codebreaker-sqlserver
      branch-name: main

  publishdevops:
    uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-azuredevops.yml@main
    needs: build
    with:
      artifact-name: codebreaker-sqlserver
    secrets: inherit

  # publishnuget:
  #   uses: CodebreakerApp/Codebreaker.Backend/.github/workflows/publishnuget-nugetserver.yml@main
  #   needs: publishdevops
  #   with:
  #     artifact-name: codebreaker-sqlserver
  #   secrets: inherit
